sudo: required 
services:
  - docker 

before_install:
  - docker run -f Dockerfile.dev -t nlrcmani/simplereactdockerfrontend . 

script:
  - docker run nlrcmani/simplereactdockerfrontend npm run test -- -- coverage 