sudo: required 
language: generic
services:
  - docker 

before_install:
  - docker build -f Dockerfile.dev -t nlrcmani/simplereactdockerfrontend . 

script:
  - docker run -e CI=true nlrcmani/simplereactdockerfrontend npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "docker-react-2"
  bucket_name: "elasticbeanstalk-us-west-2-949433743831"
  bucket_path: "docker-react"
  on:
   branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY