sudo: required 
language: generic
services:
  - docker 

before_install:
  - docker run -f Dockerfile.dev -t nlrcmani/simplereactdockerfrontend . 

script:
  - docker run e CI=true nlrcmani/simplereactdockerfrontend npm run test -- -- coverage 